### ISSUE TITLE
cant install?

### ISSUE THREAD

**Issue by buzztiaan** [Coldcard/ckcc-protocol#4]
```
buzz@h81m:~$ pip search ckcc
ckcc-protocol (0.7.2)  - Communicate with your Coldcard using Python
buzz@h81m:~$ pip install ckcc-protocol
Collecting ckcc-protocol
  Could not find a version that satisfies the requirement ckcc-protocol (from versions: )
No matching distribution found for ckcc-protocol
buzz@h81m:~$ 

```

what does this depend on? whats it trying to error on?

**Comment by peter-conalgo** [comment]
I think that could be wrong python version. We need 3.5+. 

Pip would handle/complain better about the other dependancies, IIRC.

**Comment by buzztiaan** [comment]
then the manual should mention python3 , its pip client isnt called 'pip' on many distros

**Comment by buzztiaan** [comment]
yep, pip3 works, thanks

**Comment by buzztiaan** [comment]
also required ; libusb-1.0-0-dev

**Comment by buzztiaan** [comment]
shouldnt you only close this after you update the documentation?
